apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: myapp-dev
namePrefix: dev-

commonLabels:
  environment: development

replicas:
- name: myapp
  count: 1

images:
- name: myapp
  newTag: dev-latest

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: myapp-config
    data:
      LOG_LEVEL: debug
      ENVIRONMENT: development
